Update README.md
SVijayB/JavaSpace pull request #15
Opened 2020-10-10 14:20 UTC by Vishnurr2k01

### Description

### Related Issue

This PR closes # 

### Motivation and Context

### Screenshots (if any)

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.

2020-10-10 14:21 UTC, Vishnurr2k01 commented
i have added a new problem in basics namely factorial.java

2020-10-11 06:22 UTC, SVijayB commented
Hey, you added the commit hashcode instead of the program. Can you check that and update the URL?

2020-10-11 06:25 UTC, Vishnurr2k01 commented
Sorry , iam new to github and this is my first project.I will try to
correct that..
Thank you

On Sun 11 Oct, 2020, 11:52 AM Vijay, <notifications@github.com> wrote:

> Hey, you added the commit hashcode instead of the program. Can you check
> that and update the URL?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/SVijayB/JavaSpace/pull/15#issuecomment-706656919>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARIF7TP5QA2KZ32W4A6LDRLSKFFMDANCNFSM4SLDARBA>
> .
>

2020-10-11 06:26 UTC, SVijayB requested changes

2020-10-11 06:26 UTC, SVijayB commented on README.md
> + < a href="https://github.com/SVijayB/JavaSpace/commit/b5c371a9ceeb2795d98eb315afb79459f785b9fb">factorial.java</a>| find factorial of a number
Here, you just need to update the URL to https://github.com/SVijayB/JavaSpace/blob/master/Basics/factorail.java.

2020-10-11 06:28 UTC, Vishnurr2k01 commented
OK bro...I will update it as soon as possible
Thank you

On Sun 11 Oct, 2020, 11:57 AM Vijay, <notifications@github.com> wrote:

> *@SVijayB* requested changes on this pull request.
> ------------------------------
>
> In README.md
> <https://github.com/SVijayB/JavaSpace/pull/15#discussion_r502872271>:
>
> > @@ -47,6 +47,7 @@ Basics of Java are covered within these programs.
>
>  • <a href="https://github.com/SVijayB/JavaSpace/blob/master/Basics/sorting.java">Sorting.java</a>                  | Sorting N numbers.
>
>  • <a href="https://github.com/SVijayB/JavaSpace/blob/master/Basics/squares.java">Squares.java</a>                  | Print squares until N'th turn.
>
>  • <a href="https://github.com/SVijayB/JavaSpace/blob/master/Basics/tables.java">Tables.java</a>                   | Print Multiplication table.
>
> + < a href="https://github.com/SVijayB/JavaSpace/commit/b5c371a9ceeb2795d98eb315afb79459f785b9fb">factorial.java</a>| find factorial of a number
>
>
> Here, you just need to update the URL to
> https://github.com/SVijayB/JavaSpace/blob/master/Basics/factorail.java.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/SVijayB/JavaSpace/pull/15#pullrequestreview-506147676>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARIF7TPCJOG3W3ONJEUISRTSKFF37ANCNFSM4SLDARBA>
> .
>

2020-10-11 06:38 UTC, Vishnurr2k01 commented
I have created a pull request with above changes
Thankyou

On Sun 11 Oct, 2020, 11:58 AM Vishnu R, <vishnurr2k01@gmail.com> wrote:

> OK bro...I will update it as soon as possible
> Thank you
>
> On Sun 11 Oct, 2020, 11:57 AM Vijay, <notifications@github.com> wrote:
>
>> *@SVijayB* requested changes on this pull request.
>> ------------------------------
>>
>> In README.md
>> <https://github.com/SVijayB/JavaSpace/pull/15#discussion_r502872271>:
>>
>> > @@ -47,6 +47,7 @@ Basics of Java are covered within these programs.
>>
>>  • <a href="https://github.com/SVijayB/JavaSpace/blob/master/Basics/sorting.java">Sorting.java</a>                  | Sorting N numbers.
>>
>>  • <a href="https://github.com/SVijayB/JavaSpace/blob/master/Basics/squares.java">Squares.java</a>                  | Print squares until N'th turn.
>>
>>  • <a href="https://github.com/SVijayB/JavaSpace/blob/master/Basics/tables.java">Tables.java</a>                   | Print Multiplication table.
>>
>> + < a href="https://github.com/SVijayB/JavaSpace/commit/b5c371a9ceeb2795d98eb315afb79459f785b9fb">factorial.java</a>| find factorial of a number
>>
>>
>> Here, you just need to update the URL to
>> https://github.com/SVijayB/JavaSpace/blob/master/Basics/factorail.java.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/SVijayB/JavaSpace/pull/15#pullrequestreview-506147676>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ARIF7TPCJOG3W3ONJEUISRTSKFF37ANCNFSM4SLDARBA>
>> .
>>
>

2020-10-11 06:43 UTC, SVijayB commented
Issue solved at #16

2020-10-11 06:43 UTC, closed without merging